package codeGen.readWrite.data;
 /*
  *          Field Name's for DTAR022.cbl
  * ------------------------------------------------------------------   
  *
  *   This class holds the field names of Cobol-Copybook DTAR022.cbl
  *   It will allow you use code completion on <i>Cobol Field Names</i> in your
  *   java Programs 
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 26 Nov 2017 9:46:29 
  * *     from Copybook: DTAR022.cbl
  * *          Template: pojo
  * *             Split: None   
  * * File Organization: 0   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        26 Nov 2017  Initial version
  *     (Bruce Martin)
  */


public class FieldNamesDtar022 {

    public static final RecordDtar022 RECORD_DTAR022 = new RecordDtar022();

    public static class RecordDtar022 {
       public final String keycodeNo = "KEYCODE-NO";
       public final String theDate = "THE-DATE";
       public final String deptNo = "DEPT-NO";
       public final String qtySold = "QTY-SOLD";
       public final String salePrice = "SALE-PRICE";
	
    }


}

