//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 01:12:16 PM EST 
//


package net.sf.JRecord.cg.details.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LayoutSkeltons"/>
 *         &lt;element ref="{}RecordSkeltons"/>
 *         &lt;element ref="{}Options"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layoutSkeltons",
    "recordSkeltons",
    "options"
})
@XmlRootElement(name = "SkelGenDefinition")
public class SkelGenDefinition {
	
	public static final List<Skelton> EMPTY_SKELTON_LIST = new ArrayList<Skelton>(0);
	public static final List<Option> EMPTY_OPTION_LIST = new ArrayList<Option>(0);

    @XmlElement(name = "LayoutSkeltons", required = true)
    protected Skeltons layoutSkeltons;
    @XmlElement(name = "RecordSkeltons", required = true)
    protected Skeltons recordSkeltons;
    @XmlElement(name = "Options", required = true)
    protected Options options;

    public SkelGenDefinition() {
    }
    
    public SkelGenDefinition(List<Skelton> skels, List<Skelton> recordSkels) {
    	layoutSkeltons = getSkeltons(skels);
    	recordSkeltons = getSkeltons(recordSkels);
    }
    
    
    private Skeltons getSkeltons(List<Skelton> skels) {
    	Skeltons skeltons = new Skeltons();
    	
    	skeltons.skelton = skels;
    	
    	return skeltons;
    }
   
    /**
     * Gets the value of the layoutSkeltons property.
     * 
     * @return
     *     possible object is
     *     {@link Skeltons }
     *     
     */
    public List<Skelton> getLayoutSkeltons() {
        return layoutSkeltons == null ? EMPTY_SKELTON_LIST : layoutSkeltons.skelton;
    }

//    /**
//     * Sets the value of the layoutSkeltons property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link Skeltons }
//     *     
//     */
//    public void setLayoutSkeltons(Skeltons value) {
//        this.layoutSkeltons = value;
//    }

    /**
     * Gets the value of the recordSkeltons property.
     * 
     * @return
     *     possible object is
     *     {@link Skeltons }
     *     
     */
    public List<Skelton> getRecordSkeltons() {
        return recordSkeltons == null ? EMPTY_SKELTON_LIST : recordSkeltons.skelton;
    }
    
    public List<Option> getOptions() {
    	return options == null ? EMPTY_OPTION_LIST :  options.option;
    }

//    /**
//     * Sets the value of the recordSkeltons property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link Skeltons }
//     *     
//     */
//    public void setRecordSkeltons(Skeltons value) {
//        this.recordSkeltons = value;
//    }
//
//    /**
//     * Gets the value of the options property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link Options }
//     *     
//     */
//    public Options getOptions() {
//        return options;
//    }
//
//    /**
//     * Sets the value of the options property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link Options }
//     *     
//     */
//    public void setOptions(Options value) {
//        this.options = value;
//    }

}
