package net.sf.JRecord.cbl2json.zExampleGen;

/**
  * -------------------------------------------------------------------
  *
  *  Purpose:  Convert a Cobol Data file using Cobol Copybook to a Json file       
  *   Author:  RecordEditor~CodeGen
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 20 Jun 2016 13:43:8 
  * *     from Copybook: DTAR020.cbl
  * *           Dialect: FMT_MAINFRAME
  * *          Template: javaCbl2Json
  * *             Split: SPLIT_NONE   
  * * File Organization: IO_FIXED_LENGTH   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *                           
  *   This program was generated by the RecordEditor/CodeGen.
  *   It uses JRecord's Cobol2Xml programs to do the conversion. 
  *
  *   See:    RecordEditor   https://sourceforge.net/projects/record-editor/
  *           JRecord        https://sourceforge.net/projects/jrecord/  
  *
  *   Good Luck
  *              Bruce
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        20 Jun 2016  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  **/

import java.io.IOException;


import javax.xml.stream.XMLStreamException;

import net.sf.JRecord.Option.JRecordConstantVars;
import net.sf.cobolToJson.Cobol2Json;
	
public class Dtar020ToJson {

    public static void main(String[] args)
    throws IOException,  XMLStreamException {
   
        JRecordConstantVars constants = Cobol2Json.JR_CONSTANTS;
	
        Cobol2Json.newCobol2Json("G:/Users/Bruce01/RecordEditor_HSQL/CopyBook/Cobol/DTAR020.cbl")

                                         // Cobol Options
                         .setFileOrganization(constants.IO_FIXED_LENGTH)
                         .setDialect(constants.FMT_MAINFRAME)               
                         .setSplitCopybook(constants.SPLIT_NONE)      
                         .setFont("cp037")

              .cobol2json("G:/Users/Bruce01/RecordEditor_HSQL/SampleFiles/DTAR020.bin", 
                          "G:/Users/Bruce01/RecordEditor_HSQL/SampleFiles/DTAR020.bin.json");
    }
}

