package net.sf.JRecord.zTest.cg.pojo.data;

 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2025/04/24 0:0:0 
  * *     from Copybook: DTAR020
  * *          Template: pojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *     Generated for: JRecord Version 932  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most part, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2025/04/24  Initial version
  *     (Bruce Martin)
  */
                                                                    
import java.io.IOException;

import net.sf.JRecord.cgen.impl.derSer.BasePojoConverter;
import net.sf.JRecord.def.IO.builders.ISchemaIOBuilder;

import net.sf.JRecord.Common.IFieldDetail;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.Line;
import net.sf.JRecord.Details.fieldValue.IFieldValueUpdLine;
import net.sf.JRecord.Details.fieldValue.LineFieldCreator;

public class ConvertDtar020 extends BasePojoConverter<LineDtar020Pojo> {
 
    public final IFieldValueUpdLine fuKeycodeNo;
    public final IFieldValueUpdLine fuStoreNo;
    public final IFieldValueUpdLine fuDate;
    public final IFieldValueUpdLine fuDeptNo;
    public final IFieldValueUpdLine fuQtySold;
    public final IFieldValueUpdLine fuSalePrice;




                  
    public ConvertDtar020(ISchemaIOBuilder lineCreator) throws IOException {
        super(lineCreator);
        
        LayoutDetail schema = lineCreator.getLayout();
        FieldDefinitionsDtar020.RecordDtar020 fDef 
             = FieldDefinitionsDtar020.getFieldsDtar020(schema);          
        AbstractLine line = lineCreator.newLine();
        LineFieldCreator lfc = LineFieldCreator.getInstance();
                  
                   

        fuKeycodeNo = lfc.newFieldValue(line, fDef.keycodeNo);
        fuStoreNo = lfc.newFieldValue(line, fDef.storeNo);
        fuDate = lfc.newFieldValue(line, fDef.date);
        fuDeptNo = lfc.newFieldValue(line, fDef.deptNo);
        fuQtySold = lfc.newFieldValue(line, fDef.qtySold);
        fuSalePrice = lfc.newFieldValue(line, fDef.salePrice);





    }
    
	
    @Override
    public LineDtar020Pojo toPojo(AbstractLine line) { 
        
        LineDtar020Pojo pojo = new LineDtar020Pojo();
        
        pojo.setKeycodeNo(fuKeycodeNo.setLine(line).asString());
        pojo.setStoreNo((short) fuStoreNo.setLine(line).asInt());
        pojo.setDate(fuDate.setLine(line).asInt());
        pojo.setDeptNo((short) fuDeptNo.setLine(line).asInt());
        pojo.setQtySold(fuQtySold.setLine(line).asInt());
        pojo.setSalePrice(fuSalePrice.setLine(line).asBigDecimal());
	// false

                        

        return pojo;
    }

    @Override
    public void updateLine(AbstractLine line, LineDtar020Pojo pojo) {
        
        fuKeycodeNo.setLine(line).set(pojo.getKeycodeNo());
        fuStoreNo.setLine(line).set(pojo.getStoreNo());
        fuDate.setLine(line).set(pojo.getDate());
        fuDeptNo.setLine(line).set(pojo.getDeptNo());
        fuQtySold.setLine(line).set(pojo.getQtySold());
        fuSalePrice.setLine(line).set(pojo.getSalePrice());
    
    }
    
	
}
