package net.sf.JRecord.zTest.cg.pojo.data;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2025/04/24 0:0:0 
  * *     from Copybook: DTAR020
  * *          Template: pojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *     Generated for: JRecord Version 932  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most part, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2025/04/24  Initial version
  *     (Bruce Martin)
  */
	

import java.math.BigDecimal;


/**
 * This class represents the Cobol Record ( <b>DTAR020</b>)
 * from the file (copybook  DTAR020).
 */
public class LineDtar020Pojo 
 {

	
    private String keycodeNo;
    private short storeNo;
    private int date;
    private short deptNo;
    private int qtySold;
    private BigDecimal salePrice;




	/**
	 *  Get Cobol Field DTAR020-KEYCODE-NO     Pic X(08)      (Position/Length 1/8)
	 */	
    
    public String getKeycodeNo() {
        return keycodeNo;
    }
    
	/**
	 *  Set Cobol Field DTAR020-KEYCODE-NO     Pic X(08)      (Position/Length 1/8)
	 */	
    
    public void setKeycodeNo(String value) {
        this.keycodeNo = value;
    }

	/**
	 *  Get Cobol Field DTAR020-STORE-NO     Pic S9(03)     computational-3 (Position/Length 9/2)
	 */	
    
    public short getStoreNo() {
        return storeNo;
    }
    
	/**
	 *  Set Cobol Field DTAR020-STORE-NO     Pic S9(03)     computational-3 (Position/Length 9/2)
	 */	
    
    public void setStoreNo(short value) {
        this.storeNo = value;
    }

	/**
	 *  Get Cobol Field DTAR020-DATE     Pic S9(07)     computational-3 (Position/Length 11/4)
	 */	
    
    public int getDate() {
        return date;
    }
    
	/**
	 *  Set Cobol Field DTAR020-DATE     Pic S9(07)     computational-3 (Position/Length 11/4)
	 */	
    
    public void setDate(int value) {
        this.date = value;
    }

	/**
	 *  Get Cobol Field DTAR020-DEPT-NO     Pic S9(03)     computational-3 (Position/Length 15/2)
	 */	
    
    public short getDeptNo() {
        return deptNo;
    }
    
	/**
	 *  Set Cobol Field DTAR020-DEPT-NO     Pic S9(03)     computational-3 (Position/Length 15/2)
	 */	
    
    public void setDeptNo(short value) {
        this.deptNo = value;
    }

	/**
	 *  Get Cobol Field DTAR020-QTY-SOLD     Pic S9(9)     computational-3 (Position/Length 17/5)
	 */	
    
    public int getQtySold() {
        return qtySold;
    }
    
	/**
	 *  Set Cobol Field DTAR020-QTY-SOLD     Pic S9(9)     computational-3 (Position/Length 17/5)
	 */	
    
    public void setQtySold(int value) {
        this.qtySold = value;
    }

	/**
	 *  Get Cobol Field DTAR020-SALE-PRICE     Pic S9(9)V99     computational-3 (Position/Length 22/6)
	 */	
    
    public BigDecimal getSalePrice() {
        return salePrice;
    }
    
	/**
	 *  Set Cobol Field DTAR020-SALE-PRICE     Pic S9(9)V99     computational-3 (Position/Length 22/6)
	 */	
    
    public void setSalePrice(BigDecimal value) {
        this.salePrice = value;
    }



	

}
