/*  -------------------------------------------------------------------------
 *
 *            Sub-Project: JRecord IOBuilder examples
 *    
 *    Sub-Project purpose: Examples of using JRecord IOBuilders
 *                        to perform IO on Cobol Data files
 *    
 *                 Author: Bruce Martin
 *    
 *                License: LGPL 2.1 or latter
 *                
 *    Copyright (c) 2016, Bruce Martin, All Rights Reserved.
 *   
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *   
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Lesser General Public License for more details.
 *
 * ------------------------------------------------------------------------ */
      
package net.sf.JRecord.zExamples.iob.cobol.iobuilder;

/**
 * This class holds the Cobol fields names as constants.
 * So rather than having to remember the Cobol-Names use your
 * IDE's auto assist instead.
 *
 * There could be duplicate field names, I will leave you to sort this out
 *
 * Code Generated by the Recordeditor (Author: Bruce Martin)
 */

public class Dtar020 {

    public static final ClassDtar020 DTAR020 = new ClassDtar020();


    public static final class ClassDtar020 { 

        public final String recordName = "DTAR020";

        public final String keycodeNo = "DTAR020-KEYCODE-NO";
        public final String storeNo = "DTAR020-STORE-NO";
        public final String date = "DTAR020-DATE";
        public final String deptNo = "DTAR020-DEPT-NO";
        public final String qtySold = "DTAR020-QTY-SOLD";
        public final String salePrice = "DTAR020-SALE-PRICE";

    }

}