//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 01:12:16 PM EST 
//


package net.sf.JRecord.cg.details.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sf.JRecord.cg.details.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecordSkeltons_QNAME = new QName("", "RecordSkeltons");
    private final static QName _LayoutSkeltons_QNAME = new QName("", "LayoutSkeltons");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.JRecord.cg.details.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Skelton }
     * 
     */
    public Skelton createSkelton() {
        return new Skelton();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Skeltons }
     * 
     */
    public Skeltons createSkeltons() {
        return new Skeltons();
    }

    /**
     * Create an instance of {@link SkelGenDefinition }
     * 
     */
    public SkelGenDefinition createSkelGenDefinition() {
        return new SkelGenDefinition();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Skeltons }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RecordSkeltons")
    public JAXBElement<Skeltons> createRecordSkeltons(Skeltons value) {
        return new JAXBElement<Skeltons>(_RecordSkeltons_QNAME, Skeltons.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Skeltons }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LayoutSkeltons")
    public JAXBElement<Skeltons> createLayoutSkeltons(Skeltons value) {
        return new JAXBElement<Skeltons>(_LayoutSkeltons_QNAME, Skeltons.class, null, value);
    }

}
