package net.sf.JRecord.cbl2xml.zTest.xml2cbl.occursDepending;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;


import javax.xml.stream.XMLStreamException;

import junit.framework.TestCase;
import net.sf.JRecord.Numeric.ICopybookDialects;
import net.sf.JRecord.cbl2xml.Cobol2Xml;
import net.sf.JRecord.cbl2xml.def.ICobol2Xml;
import net.sf.JRecord.cbl2xml.zTest.xml2cbl.TstXmlConstants;


/**
 * This class tests Occurs Depending when 'Size' field is in a 
 * normal Array
 * 
 * @author Bruce Martin
 *
 */
public class TstOccursDepending61 extends TestCase {
	private static String[] LINES = {
			"line 0     0>1 00000 1>2 00010 00011 2>3 00020 00021 00022 3>4 00030 00031 00032 00033",
			"line 1     0>2 00100 00101 1>3 00110 00111 00112 2>4 00120 00121 00122 00123 3>5 00130 00131 00132 00133 00134",
			"line 2     0>3 00200 00201 00202 1>4 00210 00211 00212 00213 2>5 00220 00221 00222 00223 00224 3>1 00230",
			"line 3     0>4 00300 00301 00302 00303 1>5 00310 00311 00312 00313 00314 2>1 00320 3>2 00330 00331",
			"line 4     0>5 00400 00401 00402 00403 00404 1>1 00410 2>2 00420 00421 3>3 00430 00431 00432",
			"line 5     0>1 00500 1>2 00510 00511 2>3 00520 00521 00522 3>4 00530 00531 00532 00533",
			"line 6     0>2 00600 00601 1>3 00610 00611 00612 2>4 00620 00621 00622 00623 3>5 00630 00631 00632 00633 00634",
			"line 7     0>3 00700 00701 00702 1>4 00710 00711 00712 00713 2>5 00720 00721 00722 00723 00724 3>1 00730",
			"line 8     0>4 00800 00801 00802 00803 1>5 00810 00811 00812 00813 00814 2>1 00820 3>2 00830 00831",
			"line 9     0>5 00900 00901 00902 00903 00904 1>1 00910 2>2 00920 00921 3>3 00930 00931 00932",
			"line 10    0>1 01000 1>2 01010 01011 2>3 01020 01021 01022 3>4 01030 01031 01032 01033",
			"line 11    0>2 01100 01101 1>3 01110 01111 01112 2>4 01120 01121 01122 01123 3>5 01130 01131 01132 01133 01134",
			"line 12    0>3 01200 01201 01202 1>4 01210 01211 01212 01213 2>5 01220 01221 01222 01223 01224 3>1 01230",
			"line 13    0>4 01300 01301 01302 01303 1>5 01310 01311 01312 01313 01314 2>1 01320 3>2 01330 01331",
			"line 14    0>5 01400 01401 01402 01403 01404 1>1 01410 2>2 01420 01421 3>3 01430 01431 01432",
			"line 15    0>1 01500 1>2 01510 01511 2>3 01520 01521 01522 3>4 01530 01531 01532 01533",
			"line 16    0>2 01600 01601 1>3 01610 01611 01612 2>4 01620 01621 01622 01623 3>5 01630 01631 01632 01633 01634",
			"line 17    0>3 01700 01701 01702 1>4 01710 01711 01712 01713 2>5 01720 01721 01722 01723 01724 3>1 01730",
			"line 18    0>4 01800 01801 01802 01803 1>5 01810 01811 01812 01813 01814 2>1 01820 3>2 01830 01831",
			"line 19    0>5 01900 01901 01902 01903 01904 1>1 01910 2>2 01920 01921 3>3 01930 01931 01932",
			"line 20    0>1 02000 1>2 02010 02011 2>3 02020 02021 02022 3>4 02030 02031 02032 02033",
			"line 21    0>2 02100 02101 1>3 02110 02111 02112 2>4 02120 02121 02122 02123 3>5 02130 02131 02132 02133 02134",
			"line 22    0>3 02200 02201 02202 1>4 02210 02211 02212 02213 2>5 02220 02221 02222 02223 02224 3>1 02230",
			"line 23    0>4 02300 02301 02302 02303 1>5 02310 02311 02312 02313 02314 2>1 02320 3>2 02330 02331",
			"line 24    0>5 02400 02401 02402 02403 02404 1>1 02410 2>2 02420 02421 3>3 02430 02431 02432",
			"line 25    0>1 02500 1>2 02510 02511 2>3 02520 02521 02522 3>4 02530 02531 02532 02533",
			"line 26    0>2 02600 02601 1>3 02610 02611 02612 2>4 02620 02621 02622 02623 3>5 02630 02631 02632 02633 02634",
			"line 27    0>3 02700 02701 02702 1>4 02710 02711 02712 02713 2>5 02720 02721 02722 02723 02724 3>1 02730",
			"line 28    0>4 02800 02801 02802 02803 1>5 02810 02811 02812 02813 02814 2>1 02820 3>2 02830 02831",
			"line 29    0>5 02900 02901 02902 02903 02904 1>1 02910 2>2 02920 02921 3>3 02930 02931 02932"
	};
	private static String[] EXPECTED_XML1 = {
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 0</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>0</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>10</daily-sales></filler><filler><Sep></Sep><daily-sales>11</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>20</daily-sales></filler><filler><Sep></Sep><daily-sales>21</daily-sales></filler><filler><Sep></Sep><daily-sales>22</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>30</daily-sales></filler><filler><Sep></Sep><daily-sales>31</daily-sales></filler><filler><Sep></Sep><daily-sales>32</daily-sales></filler><filler><Sep></Sep><daily-sales>33</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 1</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>100</daily-sales></filler><filler><Sep></Sep><daily-sales>101</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>110</daily-sales></filler><filler><Sep></Sep><daily-sales>111</daily-sales></filler><filler><Sep></Sep><daily-sales>112</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>120</daily-sales></filler><filler><Sep></Sep><daily-sales>121</daily-sales></filler><filler><Sep></Sep><daily-sales>122</daily-sales></filler><filler><Sep></Sep><daily-sales>123</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>130</daily-sales></filler><filler><Sep></Sep><daily-sales>131</daily-sales></filler><filler><Sep></Sep><daily-sales>132</daily-sales></filler><filler><Sep></Sep><daily-sales>133</daily-sales></filler><filler><Sep></Sep><daily-sales>134</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 2</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>200</daily-sales></filler><filler><Sep></Sep><daily-sales>201</daily-sales></filler><filler><Sep></Sep><daily-sales>202</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>210</daily-sales></filler><filler><Sep></Sep><daily-sales>211</daily-sales></filler><filler><Sep></Sep><daily-sales>212</daily-sales></filler><filler><Sep></Sep><daily-sales>213</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>220</daily-sales></filler><filler><Sep></Sep><daily-sales>221</daily-sales></filler><filler><Sep></Sep><daily-sales>222</daily-sales></filler><filler><Sep></Sep><daily-sales>223</daily-sales></filler><filler><Sep></Sep><daily-sales>224</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>230</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 3</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>300</daily-sales></filler><filler><Sep></Sep><daily-sales>301</daily-sales></filler><filler><Sep></Sep><daily-sales>302</daily-sales></filler><filler><Sep></Sep><daily-sales>303</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>310</daily-sales></filler><filler><Sep></Sep><daily-sales>311</daily-sales></filler><filler><Sep></Sep><daily-sales>312</daily-sales></filler><filler><Sep></Sep><daily-sales>313</daily-sales></filler><filler><Sep></Sep><daily-sales>314</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>320</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>330</daily-sales></filler><filler><Sep></Sep><daily-sales>331</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 4</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>400</daily-sales></filler><filler><Sep></Sep><daily-sales>401</daily-sales></filler><filler><Sep></Sep><daily-sales>402</daily-sales></filler><filler><Sep></Sep><daily-sales>403</daily-sales></filler><filler><Sep></Sep><daily-sales>404</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>410</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>420</daily-sales></filler><filler><Sep></Sep><daily-sales>421</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>430</daily-sales></filler><filler><Sep></Sep><daily-sales>431</daily-sales></filler><filler><Sep></Sep><daily-sales>432</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 5</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>500</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>510</daily-sales></filler><filler><Sep></Sep><daily-sales>511</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>520</daily-sales></filler><filler><Sep></Sep><daily-sales>521</daily-sales></filler><filler><Sep></Sep><daily-sales>522</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>530</daily-sales></filler><filler><Sep></Sep><daily-sales>531</daily-sales></filler><filler><Sep></Sep><daily-sales>532</daily-sales></filler><filler><Sep></Sep><daily-sales>533</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 6</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>600</daily-sales></filler><filler><Sep></Sep><daily-sales>601</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>610</daily-sales></filler><filler><Sep></Sep><daily-sales>611</daily-sales></filler><filler><Sep></Sep><daily-sales>612</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>620</daily-sales></filler><filler><Sep></Sep><daily-sales>621</daily-sales></filler><filler><Sep></Sep><daily-sales>622</daily-sales></filler><filler><Sep></Sep><daily-sales>623</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>630</daily-sales></filler><filler><Sep></Sep><daily-sales>631</daily-sales></filler><filler><Sep></Sep><daily-sales>632</daily-sales></filler><filler><Sep></Sep><daily-sales>633</daily-sales></filler><filler><Sep></Sep><daily-sales>634</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 7</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>700</daily-sales></filler><filler><Sep></Sep><daily-sales>701</daily-sales></filler><filler><Sep></Sep><daily-sales>702</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>710</daily-sales></filler><filler><Sep></Sep><daily-sales>711</daily-sales></filler><filler><Sep></Sep><daily-sales>712</daily-sales></filler><filler><Sep></Sep><daily-sales>713</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>720</daily-sales></filler><filler><Sep></Sep><daily-sales>721</daily-sales></filler><filler><Sep></Sep><daily-sales>722</daily-sales></filler><filler><Sep></Sep><daily-sales>723</daily-sales></filler><filler><Sep></Sep><daily-sales>724</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>730</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 8</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>800</daily-sales></filler><filler><Sep></Sep><daily-sales>801</daily-sales></filler><filler><Sep></Sep><daily-sales>802</daily-sales></filler><filler><Sep></Sep><daily-sales>803</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>810</daily-sales></filler><filler><Sep></Sep><daily-sales>811</daily-sales></filler><filler><Sep></Sep><daily-sales>812</daily-sales></filler><filler><Sep></Sep><daily-sales>813</daily-sales></filler><filler><Sep></Sep><daily-sales>814</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>820</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>830</daily-sales></filler><filler><Sep></Sep><daily-sales>831</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 9</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>900</daily-sales></filler><filler><Sep></Sep><daily-sales>901</daily-sales></filler><filler><Sep></Sep><daily-sales>902</daily-sales></filler><filler><Sep></Sep><daily-sales>903</daily-sales></filler><filler><Sep></Sep><daily-sales>904</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>910</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>920</daily-sales></filler><filler><Sep></Sep><daily-sales>921</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>930</daily-sales></filler><filler><Sep></Sep><daily-sales>931</daily-sales></filler><filler><Sep></Sep><daily-sales>932</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 10</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1000</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1010</daily-sales></filler><filler><Sep></Sep><daily-sales>1011</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1020</daily-sales></filler><filler><Sep></Sep><daily-sales>1021</daily-sales></filler><filler><Sep></Sep><daily-sales>1022</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1030</daily-sales></filler><filler><Sep></Sep><daily-sales>1031</daily-sales></filler><filler><Sep></Sep><daily-sales>1032</daily-sales></filler><filler><Sep></Sep><daily-sales>1033</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 11</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1100</daily-sales></filler><filler><Sep></Sep><daily-sales>1101</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1110</daily-sales></filler><filler><Sep></Sep><daily-sales>1111</daily-sales></filler><filler><Sep></Sep><daily-sales>1112</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1120</daily-sales></filler><filler><Sep></Sep><daily-sales>1121</daily-sales></filler><filler><Sep></Sep><daily-sales>1122</daily-sales></filler><filler><Sep></Sep><daily-sales>1123</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1130</daily-sales></filler><filler><Sep></Sep><daily-sales>1131</daily-sales></filler><filler><Sep></Sep><daily-sales>1132</daily-sales></filler><filler><Sep></Sep><daily-sales>1133</daily-sales></filler><filler><Sep></Sep><daily-sales>1134</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 12</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1200</daily-sales></filler><filler><Sep></Sep><daily-sales>1201</daily-sales></filler><filler><Sep></Sep><daily-sales>1202</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1210</daily-sales></filler><filler><Sep></Sep><daily-sales>1211</daily-sales></filler><filler><Sep></Sep><daily-sales>1212</daily-sales></filler><filler><Sep></Sep><daily-sales>1213</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1220</daily-sales></filler><filler><Sep></Sep><daily-sales>1221</daily-sales></filler><filler><Sep></Sep><daily-sales>1222</daily-sales></filler><filler><Sep></Sep><daily-sales>1223</daily-sales></filler><filler><Sep></Sep><daily-sales>1224</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1230</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 13</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1300</daily-sales></filler><filler><Sep></Sep><daily-sales>1301</daily-sales></filler><filler><Sep></Sep><daily-sales>1302</daily-sales></filler><filler><Sep></Sep><daily-sales>1303</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1310</daily-sales></filler><filler><Sep></Sep><daily-sales>1311</daily-sales></filler><filler><Sep></Sep><daily-sales>1312</daily-sales></filler><filler><Sep></Sep><daily-sales>1313</daily-sales></filler><filler><Sep></Sep><daily-sales>1314</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1320</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1330</daily-sales></filler><filler><Sep></Sep><daily-sales>1331</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 14</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1400</daily-sales></filler><filler><Sep></Sep><daily-sales>1401</daily-sales></filler><filler><Sep></Sep><daily-sales>1402</daily-sales></filler><filler><Sep></Sep><daily-sales>1403</daily-sales></filler><filler><Sep></Sep><daily-sales>1404</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1410</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1420</daily-sales></filler><filler><Sep></Sep><daily-sales>1421</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1430</daily-sales></filler><filler><Sep></Sep><daily-sales>1431</daily-sales></filler><filler><Sep></Sep><daily-sales>1432</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 15</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1500</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1510</daily-sales></filler><filler><Sep></Sep><daily-sales>1511</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1520</daily-sales></filler><filler><Sep></Sep><daily-sales>1521</daily-sales></filler><filler><Sep></Sep><daily-sales>1522</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1530</daily-sales></filler><filler><Sep></Sep><daily-sales>1531</daily-sales></filler><filler><Sep></Sep><daily-sales>1532</daily-sales></filler><filler><Sep></Sep><daily-sales>1533</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 16</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1600</daily-sales></filler><filler><Sep></Sep><daily-sales>1601</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1610</daily-sales></filler><filler><Sep></Sep><daily-sales>1611</daily-sales></filler><filler><Sep></Sep><daily-sales>1612</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1620</daily-sales></filler><filler><Sep></Sep><daily-sales>1621</daily-sales></filler><filler><Sep></Sep><daily-sales>1622</daily-sales></filler><filler><Sep></Sep><daily-sales>1623</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1630</daily-sales></filler><filler><Sep></Sep><daily-sales>1631</daily-sales></filler><filler><Sep></Sep><daily-sales>1632</daily-sales></filler><filler><Sep></Sep><daily-sales>1633</daily-sales></filler><filler><Sep></Sep><daily-sales>1634</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 17</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1700</daily-sales></filler><filler><Sep></Sep><daily-sales>1701</daily-sales></filler><filler><Sep></Sep><daily-sales>1702</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1710</daily-sales></filler><filler><Sep></Sep><daily-sales>1711</daily-sales></filler><filler><Sep></Sep><daily-sales>1712</daily-sales></filler><filler><Sep></Sep><daily-sales>1713</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1720</daily-sales></filler><filler><Sep></Sep><daily-sales>1721</daily-sales></filler><filler><Sep></Sep><daily-sales>1722</daily-sales></filler><filler><Sep></Sep><daily-sales>1723</daily-sales></filler><filler><Sep></Sep><daily-sales>1724</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1730</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 18</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>1800</daily-sales></filler><filler><Sep></Sep><daily-sales>1801</daily-sales></filler><filler><Sep></Sep><daily-sales>1802</daily-sales></filler><filler><Sep></Sep><daily-sales>1803</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1810</daily-sales></filler><filler><Sep></Sep><daily-sales>1811</daily-sales></filler><filler><Sep></Sep><daily-sales>1812</daily-sales></filler><filler><Sep></Sep><daily-sales>1813</daily-sales></filler><filler><Sep></Sep><daily-sales>1814</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1820</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1830</daily-sales></filler><filler><Sep></Sep><daily-sales>1831</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 19</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>1900</daily-sales></filler><filler><Sep></Sep><daily-sales>1901</daily-sales></filler><filler><Sep></Sep><daily-sales>1902</daily-sales></filler><filler><Sep></Sep><daily-sales>1903</daily-sales></filler><filler><Sep></Sep><daily-sales>1904</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>1910</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>1920</daily-sales></filler><filler><Sep></Sep><daily-sales>1921</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>1930</daily-sales></filler><filler><Sep></Sep><daily-sales>1931</daily-sales></filler><filler><Sep></Sep><daily-sales>1932</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 20</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2000</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2010</daily-sales></filler><filler><Sep></Sep><daily-sales>2011</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2020</daily-sales></filler><filler><Sep></Sep><daily-sales>2021</daily-sales></filler><filler><Sep></Sep><daily-sales>2022</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2030</daily-sales></filler><filler><Sep></Sep><daily-sales>2031</daily-sales></filler><filler><Sep></Sep><daily-sales>2032</daily-sales></filler><filler><Sep></Sep><daily-sales>2033</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 21</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2100</daily-sales></filler><filler><Sep></Sep><daily-sales>2101</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2110</daily-sales></filler><filler><Sep></Sep><daily-sales>2111</daily-sales></filler><filler><Sep></Sep><daily-sales>2112</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2120</daily-sales></filler><filler><Sep></Sep><daily-sales>2121</daily-sales></filler><filler><Sep></Sep><daily-sales>2122</daily-sales></filler><filler><Sep></Sep><daily-sales>2123</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2130</daily-sales></filler><filler><Sep></Sep><daily-sales>2131</daily-sales></filler><filler><Sep></Sep><daily-sales>2132</daily-sales></filler><filler><Sep></Sep><daily-sales>2133</daily-sales></filler><filler><Sep></Sep><daily-sales>2134</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 22</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2200</daily-sales></filler><filler><Sep></Sep><daily-sales>2201</daily-sales></filler><filler><Sep></Sep><daily-sales>2202</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2210</daily-sales></filler><filler><Sep></Sep><daily-sales>2211</daily-sales></filler><filler><Sep></Sep><daily-sales>2212</daily-sales></filler><filler><Sep></Sep><daily-sales>2213</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2220</daily-sales></filler><filler><Sep></Sep><daily-sales>2221</daily-sales></filler><filler><Sep></Sep><daily-sales>2222</daily-sales></filler><filler><Sep></Sep><daily-sales>2223</daily-sales></filler><filler><Sep></Sep><daily-sales>2224</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2230</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 23</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2300</daily-sales></filler><filler><Sep></Sep><daily-sales>2301</daily-sales></filler><filler><Sep></Sep><daily-sales>2302</daily-sales></filler><filler><Sep></Sep><daily-sales>2303</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2310</daily-sales></filler><filler><Sep></Sep><daily-sales>2311</daily-sales></filler><filler><Sep></Sep><daily-sales>2312</daily-sales></filler><filler><Sep></Sep><daily-sales>2313</daily-sales></filler><filler><Sep></Sep><daily-sales>2314</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2320</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2330</daily-sales></filler><filler><Sep></Sep><daily-sales>2331</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 24</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2400</daily-sales></filler><filler><Sep></Sep><daily-sales>2401</daily-sales></filler><filler><Sep></Sep><daily-sales>2402</daily-sales></filler><filler><Sep></Sep><daily-sales>2403</daily-sales></filler><filler><Sep></Sep><daily-sales>2404</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2410</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2420</daily-sales></filler><filler><Sep></Sep><daily-sales>2421</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2430</daily-sales></filler><filler><Sep></Sep><daily-sales>2431</daily-sales></filler><filler><Sep></Sep><daily-sales>2432</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 25</Test-id><fillers><text> 0&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2500</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2510</daily-sales></filler><filler><Sep></Sep><daily-sales>2511</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2520</daily-sales></filler><filler><Sep></Sep><daily-sales>2521</daily-sales></filler><filler><Sep></Sep><daily-sales>2522</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2530</daily-sales></filler><filler><Sep></Sep><daily-sales>2531</daily-sales></filler><filler><Sep></Sep><daily-sales>2532</daily-sales></filler><filler><Sep></Sep><daily-sales>2533</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 26</Test-id><fillers><text> 0&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2600</daily-sales></filler><filler><Sep></Sep><daily-sales>2601</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2610</daily-sales></filler><filler><Sep></Sep><daily-sales>2611</daily-sales></filler><filler><Sep></Sep><daily-sales>2612</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2620</daily-sales></filler><filler><Sep></Sep><daily-sales>2621</daily-sales></filler><filler><Sep></Sep><daily-sales>2622</daily-sales></filler><filler><Sep></Sep><daily-sales>2623</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2630</daily-sales></filler><filler><Sep></Sep><daily-sales>2631</daily-sales></filler><filler><Sep></Sep><daily-sales>2632</daily-sales></filler><filler><Sep></Sep><daily-sales>2633</daily-sales></filler><filler><Sep></Sep><daily-sales>2634</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 27</Test-id><fillers><text> 0&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2700</daily-sales></filler><filler><Sep></Sep><daily-sales>2701</daily-sales></filler><filler><Sep></Sep><daily-sales>2702</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2710</daily-sales></filler><filler><Sep></Sep><daily-sales>2711</daily-sales></filler><filler><Sep></Sep><daily-sales>2712</daily-sales></filler><filler><Sep></Sep><daily-sales>2713</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2720</daily-sales></filler><filler><Sep></Sep><daily-sales>2721</daily-sales></filler><filler><Sep></Sep><daily-sales>2722</daily-sales></filler><filler><Sep></Sep><daily-sales>2723</daily-sales></filler><filler><Sep></Sep><daily-sales>2724</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2730</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 28</Test-id><fillers><text> 0&gt;</text><week-of-month>4</week-of-month><filler><Sep></Sep><daily-sales>2800</daily-sales></filler><filler><Sep></Sep><daily-sales>2801</daily-sales></filler><filler><Sep></Sep><daily-sales>2802</daily-sales></filler><filler><Sep></Sep><daily-sales>2803</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2810</daily-sales></filler><filler><Sep></Sep><daily-sales>2811</daily-sales></filler><filler><Sep></Sep><daily-sales>2812</daily-sales></filler><filler><Sep></Sep><daily-sales>2813</daily-sales></filler><filler><Sep></Sep><daily-sales>2814</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2820</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2830</daily-sales></filler><filler><Sep></Sep><daily-sales>2831</daily-sales></filler></fillers></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 29</Test-id><fillers><text> 0&gt;</text><week-of-month>5</week-of-month><filler><Sep></Sep><daily-sales>2900</daily-sales></filler><filler><Sep></Sep><daily-sales>2901</daily-sales></filler><filler><Sep></Sep><daily-sales>2902</daily-sales></filler><filler><Sep></Sep><daily-sales>2903</daily-sales></filler><filler><Sep></Sep><daily-sales>2904</daily-sales></filler></fillers><fillers><text> 1&gt;</text><week-of-month>1</week-of-month><filler><Sep></Sep><daily-sales>2910</daily-sales></filler></fillers><fillers><text> 2&gt;</text><week-of-month>2</week-of-month><filler><Sep></Sep><daily-sales>2920</daily-sales></filler><filler><Sep></Sep><daily-sales>2921</daily-sales></filler></fillers><fillers><text> 3&gt;</text><week-of-month>3</week-of-month><filler><Sep></Sep><daily-sales>2930</daily-sales></filler><filler><Sep></Sep><daily-sales>2931</daily-sales></filler><filler><Sep></Sep><daily-sales>2932</daily-sales></filler></fillers></Location-Details></CobolData>",
	};
	private static String[] EXPECTED_XML2 = {
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 0</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>0</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>10</daily-sales></week><week><Sep></Sep><daily-sales>11</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>20</daily-sales></week><week><Sep></Sep><daily-sales>21</daily-sales></week><week><Sep></Sep><daily-sales>22</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>30</daily-sales></week><week><Sep></Sep><daily-sales>31</daily-sales></week><week><Sep></Sep><daily-sales>32</daily-sales></week><week><Sep></Sep><daily-sales>33</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 1</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>100</daily-sales></week><week><Sep></Sep><daily-sales>101</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>110</daily-sales></week><week><Sep></Sep><daily-sales>111</daily-sales></week><week><Sep></Sep><daily-sales>112</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>120</daily-sales></week><week><Sep></Sep><daily-sales>121</daily-sales></week><week><Sep></Sep><daily-sales>122</daily-sales></week><week><Sep></Sep><daily-sales>123</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>130</daily-sales></week><week><Sep></Sep><daily-sales>131</daily-sales></week><week><Sep></Sep><daily-sales>132</daily-sales></week><week><Sep></Sep><daily-sales>133</daily-sales></week><week><Sep></Sep><daily-sales>134</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 2</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>200</daily-sales></week><week><Sep></Sep><daily-sales>201</daily-sales></week><week><Sep></Sep><daily-sales>202</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>210</daily-sales></week><week><Sep></Sep><daily-sales>211</daily-sales></week><week><Sep></Sep><daily-sales>212</daily-sales></week><week><Sep></Sep><daily-sales>213</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>220</daily-sales></week><week><Sep></Sep><daily-sales>221</daily-sales></week><week><Sep></Sep><daily-sales>222</daily-sales></week><week><Sep></Sep><daily-sales>223</daily-sales></week><week><Sep></Sep><daily-sales>224</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>230</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 3</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>300</daily-sales></week><week><Sep></Sep><daily-sales>301</daily-sales></week><week><Sep></Sep><daily-sales>302</daily-sales></week><week><Sep></Sep><daily-sales>303</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>310</daily-sales></week><week><Sep></Sep><daily-sales>311</daily-sales></week><week><Sep></Sep><daily-sales>312</daily-sales></week><week><Sep></Sep><daily-sales>313</daily-sales></week><week><Sep></Sep><daily-sales>314</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>320</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>330</daily-sales></week><week><Sep></Sep><daily-sales>331</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 4</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>400</daily-sales></week><week><Sep></Sep><daily-sales>401</daily-sales></week><week><Sep></Sep><daily-sales>402</daily-sales></week><week><Sep></Sep><daily-sales>403</daily-sales></week><week><Sep></Sep><daily-sales>404</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>410</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>420</daily-sales></week><week><Sep></Sep><daily-sales>421</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>430</daily-sales></week><week><Sep></Sep><daily-sales>431</daily-sales></week><week><Sep></Sep><daily-sales>432</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 5</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>500</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>510</daily-sales></week><week><Sep></Sep><daily-sales>511</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>520</daily-sales></week><week><Sep></Sep><daily-sales>521</daily-sales></week><week><Sep></Sep><daily-sales>522</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>530</daily-sales></week><week><Sep></Sep><daily-sales>531</daily-sales></week><week><Sep></Sep><daily-sales>532</daily-sales></week><week><Sep></Sep><daily-sales>533</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 6</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>600</daily-sales></week><week><Sep></Sep><daily-sales>601</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>610</daily-sales></week><week><Sep></Sep><daily-sales>611</daily-sales></week><week><Sep></Sep><daily-sales>612</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>620</daily-sales></week><week><Sep></Sep><daily-sales>621</daily-sales></week><week><Sep></Sep><daily-sales>622</daily-sales></week><week><Sep></Sep><daily-sales>623</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>630</daily-sales></week><week><Sep></Sep><daily-sales>631</daily-sales></week><week><Sep></Sep><daily-sales>632</daily-sales></week><week><Sep></Sep><daily-sales>633</daily-sales></week><week><Sep></Sep><daily-sales>634</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 7</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>700</daily-sales></week><week><Sep></Sep><daily-sales>701</daily-sales></week><week><Sep></Sep><daily-sales>702</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>710</daily-sales></week><week><Sep></Sep><daily-sales>711</daily-sales></week><week><Sep></Sep><daily-sales>712</daily-sales></week><week><Sep></Sep><daily-sales>713</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>720</daily-sales></week><week><Sep></Sep><daily-sales>721</daily-sales></week><week><Sep></Sep><daily-sales>722</daily-sales></week><week><Sep></Sep><daily-sales>723</daily-sales></week><week><Sep></Sep><daily-sales>724</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>730</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 8</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>800</daily-sales></week><week><Sep></Sep><daily-sales>801</daily-sales></week><week><Sep></Sep><daily-sales>802</daily-sales></week><week><Sep></Sep><daily-sales>803</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>810</daily-sales></week><week><Sep></Sep><daily-sales>811</daily-sales></week><week><Sep></Sep><daily-sales>812</daily-sales></week><week><Sep></Sep><daily-sales>813</daily-sales></week><week><Sep></Sep><daily-sales>814</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>820</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>830</daily-sales></week><week><Sep></Sep><daily-sales>831</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 9</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>900</daily-sales></week><week><Sep></Sep><daily-sales>901</daily-sales></week><week><Sep></Sep><daily-sales>902</daily-sales></week><week><Sep></Sep><daily-sales>903</daily-sales></week><week><Sep></Sep><daily-sales>904</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>910</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>920</daily-sales></week><week><Sep></Sep><daily-sales>921</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>930</daily-sales></week><week><Sep></Sep><daily-sales>931</daily-sales></week><week><Sep></Sep><daily-sales>932</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 10</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1000</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1010</daily-sales></week><week><Sep></Sep><daily-sales>1011</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1020</daily-sales></week><week><Sep></Sep><daily-sales>1021</daily-sales></week><week><Sep></Sep><daily-sales>1022</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1030</daily-sales></week><week><Sep></Sep><daily-sales>1031</daily-sales></week><week><Sep></Sep><daily-sales>1032</daily-sales></week><week><Sep></Sep><daily-sales>1033</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 11</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1100</daily-sales></week><week><Sep></Sep><daily-sales>1101</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1110</daily-sales></week><week><Sep></Sep><daily-sales>1111</daily-sales></week><week><Sep></Sep><daily-sales>1112</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1120</daily-sales></week><week><Sep></Sep><daily-sales>1121</daily-sales></week><week><Sep></Sep><daily-sales>1122</daily-sales></week><week><Sep></Sep><daily-sales>1123</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1130</daily-sales></week><week><Sep></Sep><daily-sales>1131</daily-sales></week><week><Sep></Sep><daily-sales>1132</daily-sales></week><week><Sep></Sep><daily-sales>1133</daily-sales></week><week><Sep></Sep><daily-sales>1134</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 12</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1200</daily-sales></week><week><Sep></Sep><daily-sales>1201</daily-sales></week><week><Sep></Sep><daily-sales>1202</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1210</daily-sales></week><week><Sep></Sep><daily-sales>1211</daily-sales></week><week><Sep></Sep><daily-sales>1212</daily-sales></week><week><Sep></Sep><daily-sales>1213</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1220</daily-sales></week><week><Sep></Sep><daily-sales>1221</daily-sales></week><week><Sep></Sep><daily-sales>1222</daily-sales></week><week><Sep></Sep><daily-sales>1223</daily-sales></week><week><Sep></Sep><daily-sales>1224</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1230</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 13</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1300</daily-sales></week><week><Sep></Sep><daily-sales>1301</daily-sales></week><week><Sep></Sep><daily-sales>1302</daily-sales></week><week><Sep></Sep><daily-sales>1303</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1310</daily-sales></week><week><Sep></Sep><daily-sales>1311</daily-sales></week><week><Sep></Sep><daily-sales>1312</daily-sales></week><week><Sep></Sep><daily-sales>1313</daily-sales></week><week><Sep></Sep><daily-sales>1314</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1320</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1330</daily-sales></week><week><Sep></Sep><daily-sales>1331</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 14</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1400</daily-sales></week><week><Sep></Sep><daily-sales>1401</daily-sales></week><week><Sep></Sep><daily-sales>1402</daily-sales></week><week><Sep></Sep><daily-sales>1403</daily-sales></week><week><Sep></Sep><daily-sales>1404</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1410</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1420</daily-sales></week><week><Sep></Sep><daily-sales>1421</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1430</daily-sales></week><week><Sep></Sep><daily-sales>1431</daily-sales></week><week><Sep></Sep><daily-sales>1432</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 15</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1500</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1510</daily-sales></week><week><Sep></Sep><daily-sales>1511</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1520</daily-sales></week><week><Sep></Sep><daily-sales>1521</daily-sales></week><week><Sep></Sep><daily-sales>1522</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1530</daily-sales></week><week><Sep></Sep><daily-sales>1531</daily-sales></week><week><Sep></Sep><daily-sales>1532</daily-sales></week><week><Sep></Sep><daily-sales>1533</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 16</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1600</daily-sales></week><week><Sep></Sep><daily-sales>1601</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1610</daily-sales></week><week><Sep></Sep><daily-sales>1611</daily-sales></week><week><Sep></Sep><daily-sales>1612</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1620</daily-sales></week><week><Sep></Sep><daily-sales>1621</daily-sales></week><week><Sep></Sep><daily-sales>1622</daily-sales></week><week><Sep></Sep><daily-sales>1623</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1630</daily-sales></week><week><Sep></Sep><daily-sales>1631</daily-sales></week><week><Sep></Sep><daily-sales>1632</daily-sales></week><week><Sep></Sep><daily-sales>1633</daily-sales></week><week><Sep></Sep><daily-sales>1634</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 17</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1700</daily-sales></week><week><Sep></Sep><daily-sales>1701</daily-sales></week><week><Sep></Sep><daily-sales>1702</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1710</daily-sales></week><week><Sep></Sep><daily-sales>1711</daily-sales></week><week><Sep></Sep><daily-sales>1712</daily-sales></week><week><Sep></Sep><daily-sales>1713</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1720</daily-sales></week><week><Sep></Sep><daily-sales>1721</daily-sales></week><week><Sep></Sep><daily-sales>1722</daily-sales></week><week><Sep></Sep><daily-sales>1723</daily-sales></week><week><Sep></Sep><daily-sales>1724</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1730</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 18</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>1800</daily-sales></week><week><Sep></Sep><daily-sales>1801</daily-sales></week><week><Sep></Sep><daily-sales>1802</daily-sales></week><week><Sep></Sep><daily-sales>1803</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1810</daily-sales></week><week><Sep></Sep><daily-sales>1811</daily-sales></week><week><Sep></Sep><daily-sales>1812</daily-sales></week><week><Sep></Sep><daily-sales>1813</daily-sales></week><week><Sep></Sep><daily-sales>1814</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1820</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1830</daily-sales></week><week><Sep></Sep><daily-sales>1831</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 19</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>1900</daily-sales></week><week><Sep></Sep><daily-sales>1901</daily-sales></week><week><Sep></Sep><daily-sales>1902</daily-sales></week><week><Sep></Sep><daily-sales>1903</daily-sales></week><week><Sep></Sep><daily-sales>1904</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>1910</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>1920</daily-sales></week><week><Sep></Sep><daily-sales>1921</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>1930</daily-sales></week><week><Sep></Sep><daily-sales>1931</daily-sales></week><week><Sep></Sep><daily-sales>1932</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 20</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2000</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2010</daily-sales></week><week><Sep></Sep><daily-sales>2011</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2020</daily-sales></week><week><Sep></Sep><daily-sales>2021</daily-sales></week><week><Sep></Sep><daily-sales>2022</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2030</daily-sales></week><week><Sep></Sep><daily-sales>2031</daily-sales></week><week><Sep></Sep><daily-sales>2032</daily-sales></week><week><Sep></Sep><daily-sales>2033</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 21</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2100</daily-sales></week><week><Sep></Sep><daily-sales>2101</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2110</daily-sales></week><week><Sep></Sep><daily-sales>2111</daily-sales></week><week><Sep></Sep><daily-sales>2112</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2120</daily-sales></week><week><Sep></Sep><daily-sales>2121</daily-sales></week><week><Sep></Sep><daily-sales>2122</daily-sales></week><week><Sep></Sep><daily-sales>2123</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2130</daily-sales></week><week><Sep></Sep><daily-sales>2131</daily-sales></week><week><Sep></Sep><daily-sales>2132</daily-sales></week><week><Sep></Sep><daily-sales>2133</daily-sales></week><week><Sep></Sep><daily-sales>2134</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 22</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2200</daily-sales></week><week><Sep></Sep><daily-sales>2201</daily-sales></week><week><Sep></Sep><daily-sales>2202</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2210</daily-sales></week><week><Sep></Sep><daily-sales>2211</daily-sales></week><week><Sep></Sep><daily-sales>2212</daily-sales></week><week><Sep></Sep><daily-sales>2213</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2220</daily-sales></week><week><Sep></Sep><daily-sales>2221</daily-sales></week><week><Sep></Sep><daily-sales>2222</daily-sales></week><week><Sep></Sep><daily-sales>2223</daily-sales></week><week><Sep></Sep><daily-sales>2224</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2230</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 23</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2300</daily-sales></week><week><Sep></Sep><daily-sales>2301</daily-sales></week><week><Sep></Sep><daily-sales>2302</daily-sales></week><week><Sep></Sep><daily-sales>2303</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2310</daily-sales></week><week><Sep></Sep><daily-sales>2311</daily-sales></week><week><Sep></Sep><daily-sales>2312</daily-sales></week><week><Sep></Sep><daily-sales>2313</daily-sales></week><week><Sep></Sep><daily-sales>2314</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2320</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2330</daily-sales></week><week><Sep></Sep><daily-sales>2331</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 24</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2400</daily-sales></week><week><Sep></Sep><daily-sales>2401</daily-sales></week><week><Sep></Sep><daily-sales>2402</daily-sales></week><week><Sep></Sep><daily-sales>2403</daily-sales></week><week><Sep></Sep><daily-sales>2404</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2410</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2420</daily-sales></week><week><Sep></Sep><daily-sales>2421</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2430</daily-sales></week><week><Sep></Sep><daily-sales>2431</daily-sales></week><week><Sep></Sep><daily-sales>2432</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 25</Test-id><a4><text> 0&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2500</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2510</daily-sales></week><week><Sep></Sep><daily-sales>2511</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2520</daily-sales></week><week><Sep></Sep><daily-sales>2521</daily-sales></week><week><Sep></Sep><daily-sales>2522</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2530</daily-sales></week><week><Sep></Sep><daily-sales>2531</daily-sales></week><week><Sep></Sep><daily-sales>2532</daily-sales></week><week><Sep></Sep><daily-sales>2533</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 26</Test-id><a4><text> 0&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2600</daily-sales></week><week><Sep></Sep><daily-sales>2601</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2610</daily-sales></week><week><Sep></Sep><daily-sales>2611</daily-sales></week><week><Sep></Sep><daily-sales>2612</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2620</daily-sales></week><week><Sep></Sep><daily-sales>2621</daily-sales></week><week><Sep></Sep><daily-sales>2622</daily-sales></week><week><Sep></Sep><daily-sales>2623</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2630</daily-sales></week><week><Sep></Sep><daily-sales>2631</daily-sales></week><week><Sep></Sep><daily-sales>2632</daily-sales></week><week><Sep></Sep><daily-sales>2633</daily-sales></week><week><Sep></Sep><daily-sales>2634</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 27</Test-id><a4><text> 0&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2700</daily-sales></week><week><Sep></Sep><daily-sales>2701</daily-sales></week><week><Sep></Sep><daily-sales>2702</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2710</daily-sales></week><week><Sep></Sep><daily-sales>2711</daily-sales></week><week><Sep></Sep><daily-sales>2712</daily-sales></week><week><Sep></Sep><daily-sales>2713</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2720</daily-sales></week><week><Sep></Sep><daily-sales>2721</daily-sales></week><week><Sep></Sep><daily-sales>2722</daily-sales></week><week><Sep></Sep><daily-sales>2723</daily-sales></week><week><Sep></Sep><daily-sales>2724</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2730</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 28</Test-id><a4><text> 0&gt;</text><week-of-month>4</week-of-month><week><Sep></Sep><daily-sales>2800</daily-sales></week><week><Sep></Sep><daily-sales>2801</daily-sales></week><week><Sep></Sep><daily-sales>2802</daily-sales></week><week><Sep></Sep><daily-sales>2803</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2810</daily-sales></week><week><Sep></Sep><daily-sales>2811</daily-sales></week><week><Sep></Sep><daily-sales>2812</daily-sales></week><week><Sep></Sep><daily-sales>2813</daily-sales></week><week><Sep></Sep><daily-sales>2814</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2820</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2830</daily-sales></week><week><Sep></Sep><daily-sales>2831</daily-sales></week></a4></Location-Details></CobolData>",
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CobolData><Location-Details><Test-id>line 29</Test-id><a4><text> 0&gt;</text><week-of-month>5</week-of-month><week><Sep></Sep><daily-sales>2900</daily-sales></week><week><Sep></Sep><daily-sales>2901</daily-sales></week><week><Sep></Sep><daily-sales>2902</daily-sales></week><week><Sep></Sep><daily-sales>2903</daily-sales></week><week><Sep></Sep><daily-sales>2904</daily-sales></week></a4><a4><text> 1&gt;</text><week-of-month>1</week-of-month><week><Sep></Sep><daily-sales>2910</daily-sales></week></a4><a4><text> 2&gt;</text><week-of-month>2</week-of-month><week><Sep></Sep><daily-sales>2920</daily-sales></week><week><Sep></Sep><daily-sales>2921</daily-sales></week></a4><a4><text> 3&gt;</text><week-of-month>3</week-of-month><week><Sep></Sep><daily-sales>2930</daily-sales></week><week><Sep></Sep><daily-sales>2931</daily-sales></week><week><Sep></Sep><daily-sales>2932</daily-sales></week></a4></Location-Details></CobolData>",
	};
//	public void testUpdate() throws IOException {
//		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61.cbl";
//		ICobolIOBuilder ioBuilder = CobolIoProvider.getInstance()
//				.newIOBuilder(copybookFileName, ICopybookDialects.FMT_MAINFRAME);
//		AbstractLine line;
//		
//		for (int i = 0; i < LINES.length; i++) {
//			line = ioBuilder.newLine();
//			line.getFieldValue("Test-id").set("line " + i);
//			
//			for (int j = 0; j < 4; j++) {
//				int count = (i + j) % 5 + 1;
//				line.getFieldValue("text (" + j + ")").set(" " + j + ">");
//				line.getFieldValue("week-of-month (" + j + ")").set(count);
//				
//				for (int k = 0; k < count; k++) {
//					String index = " (" + j + ", " + k + ")";
//					line.getFieldValue("sep" + index)          .set(" ");
//					line.getFieldValue("daily-sales" + index)  .set(i * 100 + j * 10 + k);
//				}
//			}
//			assertEquals(LINES[i], line.getFullLine());
//		}
//	}
	

	public void testConversionToXml1() throws IOException, XMLStreamException {
		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61a.cbl";

		
		ICobol2Xml cbl2Xml = Cobol2Xml.newCobol2Xml(copybookFileName)
				.setDialect(ICopybookDialects.FMT_GNU_COBOL);
		
		for (int i = 0; i < LINES.length; i++) {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			cbl2Xml.cobol2xml(new ByteArrayInputStream(LINES[i].getBytes()), os);
			
			assertEquals(EXPECTED_XML1[i], new String(os.toByteArray()));
//			System.out.println();
//			System.out.println(LINES[i]);
//			System.out.println(new String(os.toByteArray()));
		}
	}

	public void testConversionToXml2() throws IOException, XMLStreamException {
		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61.cbl";

		
		ICobol2Xml cbl2Xml = Cobol2Xml.newCobol2Xml(copybookFileName)
				.setDialect(ICopybookDialects.FMT_GNU_COBOL);
		
		for (int i = 0; i < LINES.length; i++) {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			cbl2Xml.cobol2xml(new ByteArrayInputStream(LINES[i].getBytes()), os);

			assertEquals(EXPECTED_XML2[i], new String(os.toByteArray()));

//			assertEquals(EXPECTED_XML[i], new String(os.toByteArray()));
//			System.out.println();
//			System.out.println(LINES[i]);
//			System.out.println(new String(os.toByteArray()));
		}
	}


	public void testXmlToCobol() throws IOException, XMLStreamException {
		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61.cbl";
		
		ICobol2Xml cbl2Xml = Cobol2Xml.newCobol2Xml(copybookFileName)
				.setDialect(ICopybookDialects.FMT_GNU_COBOL);
		
		for (int i = 0; i < LINES.length; i++) {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			cbl2Xml.xml2Cobol(new ByteArrayInputStream(EXPECTED_XML2[i].getBytes()), os);
			
			String actual = new String(os.toByteArray());
			while (actual.endsWith("\n") || actual.endsWith("\r")) {
				actual = actual.substring(0, actual.length() - 1);
			}
			assertEquals("> " + i, LINES[i], actual);
		}
	}

}
