package net.sf.JRecord.cbl2json.zTest.json2cbl.occursDepending;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;


import javax.xml.stream.XMLStreamException;

import junit.framework.TestCase;
import net.sf.JRecord.Common.Conversion;
import net.sf.JRecord.Numeric.ICopybookDialects;
import net.sf.JRecord.cbl2json.zTest.json2cbl.TstXmlConstants;
import net.sf.cobolToJson.Cobol2Json;
import net.sf.cobolToJson.def.ICobol2Json;


/**
 * This class tests Occurs Depending when 'Size' field is in a 
 * normal Array
 * 
 * @author Bruce Martin
 *
 */
public class TstOccursDepending61 extends TestCase {
	private static String[] LINES = {
			"line 0     0>1 00000 1>2 00010 00011 2>3 00020 00021 00022 3>4 00030 00031 00032 00033",
			"line 1     0>2 00100 00101 1>3 00110 00111 00112 2>4 00120 00121 00122 00123 3>5 00130 00131 00132 00133 00134",
			"line 2     0>3 00200 00201 00202 1>4 00210 00211 00212 00213 2>5 00220 00221 00222 00223 00224 3>1 00230",
			"line 3     0>4 00300 00301 00302 00303 1>5 00310 00311 00312 00313 00314 2>1 00320 3>2 00330 00331",
			"line 4     0>5 00400 00401 00402 00403 00404 1>1 00410 2>2 00420 00421 3>3 00430 00431 00432",
			"line 5     0>1 00500 1>2 00510 00511 2>3 00520 00521 00522 3>4 00530 00531 00532 00533",
			"line 6     0>2 00600 00601 1>3 00610 00611 00612 2>4 00620 00621 00622 00623 3>5 00630 00631 00632 00633 00634",
			"line 7     0>3 00700 00701 00702 1>4 00710 00711 00712 00713 2>5 00720 00721 00722 00723 00724 3>1 00730",
			"line 8     0>4 00800 00801 00802 00803 1>5 00810 00811 00812 00813 00814 2>1 00820 3>2 00830 00831",
			"line 9     0>5 00900 00901 00902 00903 00904 1>1 00910 2>2 00920 00921 3>3 00930 00931 00932",
			"line 10    0>1 01000 1>2 01010 01011 2>3 01020 01021 01022 3>4 01030 01031 01032 01033",
			"line 11    0>2 01100 01101 1>3 01110 01111 01112 2>4 01120 01121 01122 01123 3>5 01130 01131 01132 01133 01134",
			"line 12    0>3 01200 01201 01202 1>4 01210 01211 01212 01213 2>5 01220 01221 01222 01223 01224 3>1 01230",
			"line 13    0>4 01300 01301 01302 01303 1>5 01310 01311 01312 01313 01314 2>1 01320 3>2 01330 01331",
			"line 14    0>5 01400 01401 01402 01403 01404 1>1 01410 2>2 01420 01421 3>3 01430 01431 01432",
			"line 15    0>1 01500 1>2 01510 01511 2>3 01520 01521 01522 3>4 01530 01531 01532 01533",
			"line 16    0>2 01600 01601 1>3 01610 01611 01612 2>4 01620 01621 01622 01623 3>5 01630 01631 01632 01633 01634",
			"line 17    0>3 01700 01701 01702 1>4 01710 01711 01712 01713 2>5 01720 01721 01722 01723 01724 3>1 01730",
			"line 18    0>4 01800 01801 01802 01803 1>5 01810 01811 01812 01813 01814 2>1 01820 3>2 01830 01831",
			"line 19    0>5 01900 01901 01902 01903 01904 1>1 01910 2>2 01920 01921 3>3 01930 01931 01932",
			"line 20    0>1 02000 1>2 02010 02011 2>3 02020 02021 02022 3>4 02030 02031 02032 02033",
			"line 21    0>2 02100 02101 1>3 02110 02111 02112 2>4 02120 02121 02122 02123 3>5 02130 02131 02132 02133 02134",
			"line 22    0>3 02200 02201 02202 1>4 02210 02211 02212 02213 2>5 02220 02221 02222 02223 02224 3>1 02230",
			"line 23    0>4 02300 02301 02302 02303 1>5 02310 02311 02312 02313 02314 2>1 02320 3>2 02330 02331",
			"line 24    0>5 02400 02401 02402 02403 02404 1>1 02410 2>2 02420 02421 3>3 02430 02431 02432",
			"line 25    0>1 02500 1>2 02510 02511 2>3 02520 02521 02522 3>4 02530 02531 02532 02533",
			"line 26    0>2 02600 02601 1>3 02610 02611 02612 2>4 02620 02621 02622 02623 3>5 02630 02631 02632 02633 02634",
			"line 27    0>3 02700 02701 02702 1>4 02710 02711 02712 02713 2>5 02720 02721 02722 02723 02724 3>1 02730",
			"line 28    0>4 02800 02801 02802 02803 1>5 02810 02811 02812 02813 02814 2>1 02820 3>2 02830 02831",
			"line 29    0>5 02900 02901 02902 02903 02904 1>1 02910 2>2 02920 02921 3>3 02930 02931 02932"
	};
	private static String[] EXPECTED_JSON1 = {
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 0\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 0\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 10\n      }, {\n        \"daily-sales\" : 11\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 20\n      }, {\n        \"daily-sales\" : 21\n      }, {\n        \"daily-sales\" : 22\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 30\n      }, {\n        \"daily-sales\" : 31\n      }, {\n        \"daily-sales\" : 32\n      }, {\n        \"daily-sales\" : 33\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 1\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 100\n      }, {\n        \"daily-sales\" : 101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 110\n      }, {\n        \"daily-sales\" : 111\n      }, {\n        \"daily-sales\" : 112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 120\n      }, {\n        \"daily-sales\" : 121\n      }, {\n        \"daily-sales\" : 122\n      }, {\n        \"daily-sales\" : 123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 130\n      }, {\n        \"daily-sales\" : 131\n      }, {\n        \"daily-sales\" : 132\n      }, {\n        \"daily-sales\" : 133\n      }, {\n        \"daily-sales\" : 134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 2\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 200\n      }, {\n        \"daily-sales\" : 201\n      }, {\n        \"daily-sales\" : 202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 210\n      }, {\n        \"daily-sales\" : 211\n      }, {\n        \"daily-sales\" : 212\n      }, {\n        \"daily-sales\" : 213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 220\n      }, {\n        \"daily-sales\" : 221\n      }, {\n        \"daily-sales\" : 222\n      }, {\n        \"daily-sales\" : 223\n      }, {\n        \"daily-sales\" : 224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 3\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 300\n      }, {\n        \"daily-sales\" : 301\n      }, {\n        \"daily-sales\" : 302\n      }, {\n        \"daily-sales\" : 303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 310\n      }, {\n        \"daily-sales\" : 311\n      }, {\n        \"daily-sales\" : 312\n      }, {\n        \"daily-sales\" : 313\n      }, {\n        \"daily-sales\" : 314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 330\n      }, {\n        \"daily-sales\" : 331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 4\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 400\n      }, {\n        \"daily-sales\" : 401\n      }, {\n        \"daily-sales\" : 402\n      }, {\n        \"daily-sales\" : 403\n      }, {\n        \"daily-sales\" : 404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 420\n      }, {\n        \"daily-sales\" : 421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 430\n      }, {\n        \"daily-sales\" : 431\n      }, {\n        \"daily-sales\" : 432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 5\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 510\n      }, {\n        \"daily-sales\" : 511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 520\n      }, {\n        \"daily-sales\" : 521\n      }, {\n        \"daily-sales\" : 522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 530\n      }, {\n        \"daily-sales\" : 531\n      }, {\n        \"daily-sales\" : 532\n      }, {\n        \"daily-sales\" : 533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 6\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 600\n      }, {\n        \"daily-sales\" : 601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 610\n      }, {\n        \"daily-sales\" : 611\n      }, {\n        \"daily-sales\" : 612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 620\n      }, {\n        \"daily-sales\" : 621\n      }, {\n        \"daily-sales\" : 622\n      }, {\n        \"daily-sales\" : 623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 630\n      }, {\n        \"daily-sales\" : 631\n      }, {\n        \"daily-sales\" : 632\n      }, {\n        \"daily-sales\" : 633\n      }, {\n        \"daily-sales\" : 634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 7\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 700\n      }, {\n        \"daily-sales\" : 701\n      }, {\n        \"daily-sales\" : 702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 710\n      }, {\n        \"daily-sales\" : 711\n      }, {\n        \"daily-sales\" : 712\n      }, {\n        \"daily-sales\" : 713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 720\n      }, {\n        \"daily-sales\" : 721\n      }, {\n        \"daily-sales\" : 722\n      }, {\n        \"daily-sales\" : 723\n      }, {\n        \"daily-sales\" : 724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 8\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 800\n      }, {\n        \"daily-sales\" : 801\n      }, {\n        \"daily-sales\" : 802\n      }, {\n        \"daily-sales\" : 803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 810\n      }, {\n        \"daily-sales\" : 811\n      }, {\n        \"daily-sales\" : 812\n      }, {\n        \"daily-sales\" : 813\n      }, {\n        \"daily-sales\" : 814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 830\n      }, {\n        \"daily-sales\" : 831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 9\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 900\n      }, {\n        \"daily-sales\" : 901\n      }, {\n        \"daily-sales\" : 902\n      }, {\n        \"daily-sales\" : 903\n      }, {\n        \"daily-sales\" : 904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 920\n      }, {\n        \"daily-sales\" : 921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 930\n      }, {\n        \"daily-sales\" : 931\n      }, {\n        \"daily-sales\" : 932\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 10\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1000\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1010\n      }, {\n        \"daily-sales\" : 1011\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1020\n      }, {\n        \"daily-sales\" : 1021\n      }, {\n        \"daily-sales\" : 1022\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1030\n      }, {\n        \"daily-sales\" : 1031\n      }, {\n        \"daily-sales\" : 1032\n      }, {\n        \"daily-sales\" : 1033\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 11\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1100\n      }, {\n        \"daily-sales\" : 1101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1110\n      }, {\n        \"daily-sales\" : 1111\n      }, {\n        \"daily-sales\" : 1112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1120\n      }, {\n        \"daily-sales\" : 1121\n      }, {\n        \"daily-sales\" : 1122\n      }, {\n        \"daily-sales\" : 1123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1130\n      }, {\n        \"daily-sales\" : 1131\n      }, {\n        \"daily-sales\" : 1132\n      }, {\n        \"daily-sales\" : 1133\n      }, {\n        \"daily-sales\" : 1134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 12\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1200\n      }, {\n        \"daily-sales\" : 1201\n      }, {\n        \"daily-sales\" : 1202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1210\n      }, {\n        \"daily-sales\" : 1211\n      }, {\n        \"daily-sales\" : 1212\n      }, {\n        \"daily-sales\" : 1213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1220\n      }, {\n        \"daily-sales\" : 1221\n      }, {\n        \"daily-sales\" : 1222\n      }, {\n        \"daily-sales\" : 1223\n      }, {\n        \"daily-sales\" : 1224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 13\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1300\n      }, {\n        \"daily-sales\" : 1301\n      }, {\n        \"daily-sales\" : 1302\n      }, {\n        \"daily-sales\" : 1303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1310\n      }, {\n        \"daily-sales\" : 1311\n      }, {\n        \"daily-sales\" : 1312\n      }, {\n        \"daily-sales\" : 1313\n      }, {\n        \"daily-sales\" : 1314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1330\n      }, {\n        \"daily-sales\" : 1331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 14\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1400\n      }, {\n        \"daily-sales\" : 1401\n      }, {\n        \"daily-sales\" : 1402\n      }, {\n        \"daily-sales\" : 1403\n      }, {\n        \"daily-sales\" : 1404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1420\n      }, {\n        \"daily-sales\" : 1421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1430\n      }, {\n        \"daily-sales\" : 1431\n      }, {\n        \"daily-sales\" : 1432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 15\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1510\n      }, {\n        \"daily-sales\" : 1511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1520\n      }, {\n        \"daily-sales\" : 1521\n      }, {\n        \"daily-sales\" : 1522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1530\n      }, {\n        \"daily-sales\" : 1531\n      }, {\n        \"daily-sales\" : 1532\n      }, {\n        \"daily-sales\" : 1533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 16\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1600\n      }, {\n        \"daily-sales\" : 1601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1610\n      }, {\n        \"daily-sales\" : 1611\n      }, {\n        \"daily-sales\" : 1612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1620\n      }, {\n        \"daily-sales\" : 1621\n      }, {\n        \"daily-sales\" : 1622\n      }, {\n        \"daily-sales\" : 1623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1630\n      }, {\n        \"daily-sales\" : 1631\n      }, {\n        \"daily-sales\" : 1632\n      }, {\n        \"daily-sales\" : 1633\n      }, {\n        \"daily-sales\" : 1634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 17\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1700\n      }, {\n        \"daily-sales\" : 1701\n      }, {\n        \"daily-sales\" : 1702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1710\n      }, {\n        \"daily-sales\" : 1711\n      }, {\n        \"daily-sales\" : 1712\n      }, {\n        \"daily-sales\" : 1713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1720\n      }, {\n        \"daily-sales\" : 1721\n      }, {\n        \"daily-sales\" : 1722\n      }, {\n        \"daily-sales\" : 1723\n      }, {\n        \"daily-sales\" : 1724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 18\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 1800\n      }, {\n        \"daily-sales\" : 1801\n      }, {\n        \"daily-sales\" : 1802\n      }, {\n        \"daily-sales\" : 1803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1810\n      }, {\n        \"daily-sales\" : 1811\n      }, {\n        \"daily-sales\" : 1812\n      }, {\n        \"daily-sales\" : 1813\n      }, {\n        \"daily-sales\" : 1814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1830\n      }, {\n        \"daily-sales\" : 1831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 19\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 1900\n      }, {\n        \"daily-sales\" : 1901\n      }, {\n        \"daily-sales\" : 1902\n      }, {\n        \"daily-sales\" : 1903\n      }, {\n        \"daily-sales\" : 1904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 1910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 1920\n      }, {\n        \"daily-sales\" : 1921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 1930\n      }, {\n        \"daily-sales\" : 1931\n      }, {\n        \"daily-sales\" : 1932\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 20\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2000\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2010\n      }, {\n        \"daily-sales\" : 2011\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2020\n      }, {\n        \"daily-sales\" : 2021\n      }, {\n        \"daily-sales\" : 2022\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2030\n      }, {\n        \"daily-sales\" : 2031\n      }, {\n        \"daily-sales\" : 2032\n      }, {\n        \"daily-sales\" : 2033\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 21\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2100\n      }, {\n        \"daily-sales\" : 2101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2110\n      }, {\n        \"daily-sales\" : 2111\n      }, {\n        \"daily-sales\" : 2112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2120\n      }, {\n        \"daily-sales\" : 2121\n      }, {\n        \"daily-sales\" : 2122\n      }, {\n        \"daily-sales\" : 2123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2130\n      }, {\n        \"daily-sales\" : 2131\n      }, {\n        \"daily-sales\" : 2132\n      }, {\n        \"daily-sales\" : 2133\n      }, {\n        \"daily-sales\" : 2134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 22\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2200\n      }, {\n        \"daily-sales\" : 2201\n      }, {\n        \"daily-sales\" : 2202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2210\n      }, {\n        \"daily-sales\" : 2211\n      }, {\n        \"daily-sales\" : 2212\n      }, {\n        \"daily-sales\" : 2213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2220\n      }, {\n        \"daily-sales\" : 2221\n      }, {\n        \"daily-sales\" : 2222\n      }, {\n        \"daily-sales\" : 2223\n      }, {\n        \"daily-sales\" : 2224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 23\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2300\n      }, {\n        \"daily-sales\" : 2301\n      }, {\n        \"daily-sales\" : 2302\n      }, {\n        \"daily-sales\" : 2303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2310\n      }, {\n        \"daily-sales\" : 2311\n      }, {\n        \"daily-sales\" : 2312\n      }, {\n        \"daily-sales\" : 2313\n      }, {\n        \"daily-sales\" : 2314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2330\n      }, {\n        \"daily-sales\" : 2331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 24\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2400\n      }, {\n        \"daily-sales\" : 2401\n      }, {\n        \"daily-sales\" : 2402\n      }, {\n        \"daily-sales\" : 2403\n      }, {\n        \"daily-sales\" : 2404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2420\n      }, {\n        \"daily-sales\" : 2421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2430\n      }, {\n        \"daily-sales\" : 2431\n      }, {\n        \"daily-sales\" : 2432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 25\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2510\n      }, {\n        \"daily-sales\" : 2511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2520\n      }, {\n        \"daily-sales\" : 2521\n      }, {\n        \"daily-sales\" : 2522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2530\n      }, {\n        \"daily-sales\" : 2531\n      }, {\n        \"daily-sales\" : 2532\n      }, {\n        \"daily-sales\" : 2533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 26\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2600\n      }, {\n        \"daily-sales\" : 2601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2610\n      }, {\n        \"daily-sales\" : 2611\n      }, {\n        \"daily-sales\" : 2612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2620\n      }, {\n        \"daily-sales\" : 2621\n      }, {\n        \"daily-sales\" : 2622\n      }, {\n        \"daily-sales\" : 2623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2630\n      }, {\n        \"daily-sales\" : 2631\n      }, {\n        \"daily-sales\" : 2632\n      }, {\n        \"daily-sales\" : 2633\n      }, {\n        \"daily-sales\" : 2634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 27\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2700\n      }, {\n        \"daily-sales\" : 2701\n      }, {\n        \"daily-sales\" : 2702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2710\n      }, {\n        \"daily-sales\" : 2711\n      }, {\n        \"daily-sales\" : 2712\n      }, {\n        \"daily-sales\" : 2713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2720\n      }, {\n        \"daily-sales\" : 2721\n      }, {\n        \"daily-sales\" : 2722\n      }, {\n        \"daily-sales\" : 2723\n      }, {\n        \"daily-sales\" : 2724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 28\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"filler\" : [ {\n        \"daily-sales\" : 2800\n      }, {\n        \"daily-sales\" : 2801\n      }, {\n        \"daily-sales\" : 2802\n      }, {\n        \"daily-sales\" : 2803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2810\n      }, {\n        \"daily-sales\" : 2811\n      }, {\n        \"daily-sales\" : 2812\n      }, {\n        \"daily-sales\" : 2813\n      }, {\n        \"daily-sales\" : 2814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2830\n      }, {\n        \"daily-sales\" : 2831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 29\",\n    \"fillers\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"filler\" : [ {\n        \"daily-sales\" : 2900\n      }, {\n        \"daily-sales\" : 2901\n      }, {\n        \"daily-sales\" : 2902\n      }, {\n        \"daily-sales\" : 2903\n      }, {\n        \"daily-sales\" : 2904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"filler\" : [ {\n        \"daily-sales\" : 2910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"filler\" : [ {\n        \"daily-sales\" : 2920\n      }, {\n        \"daily-sales\" : 2921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"filler\" : [ {\n        \"daily-sales\" : 2930\n      }, {\n        \"daily-sales\" : 2931\n      }, {\n        \"daily-sales\" : 2932\n      } ]\n    } ]\n  } ]\n}",
		};
	private static String[] EXPECTED_JSON2 = {
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 0\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 0\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 10\n      }, {\n        \"daily-sales\" : 11\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 20\n      }, {\n        \"daily-sales\" : 21\n      }, {\n        \"daily-sales\" : 22\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 30\n      }, {\n        \"daily-sales\" : 31\n      }, {\n        \"daily-sales\" : 32\n      }, {\n        \"daily-sales\" : 33\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 1\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 100\n      }, {\n        \"daily-sales\" : 101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 110\n      }, {\n        \"daily-sales\" : 111\n      }, {\n        \"daily-sales\" : 112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 120\n      }, {\n        \"daily-sales\" : 121\n      }, {\n        \"daily-sales\" : 122\n      }, {\n        \"daily-sales\" : 123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 130\n      }, {\n        \"daily-sales\" : 131\n      }, {\n        \"daily-sales\" : 132\n      }, {\n        \"daily-sales\" : 133\n      }, {\n        \"daily-sales\" : 134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 2\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 200\n      }, {\n        \"daily-sales\" : 201\n      }, {\n        \"daily-sales\" : 202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 210\n      }, {\n        \"daily-sales\" : 211\n      }, {\n        \"daily-sales\" : 212\n      }, {\n        \"daily-sales\" : 213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 220\n      }, {\n        \"daily-sales\" : 221\n      }, {\n        \"daily-sales\" : 222\n      }, {\n        \"daily-sales\" : 223\n      }, {\n        \"daily-sales\" : 224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 3\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 300\n      }, {\n        \"daily-sales\" : 301\n      }, {\n        \"daily-sales\" : 302\n      }, {\n        \"daily-sales\" : 303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 310\n      }, {\n        \"daily-sales\" : 311\n      }, {\n        \"daily-sales\" : 312\n      }, {\n        \"daily-sales\" : 313\n      }, {\n        \"daily-sales\" : 314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 330\n      }, {\n        \"daily-sales\" : 331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 4\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 400\n      }, {\n        \"daily-sales\" : 401\n      }, {\n        \"daily-sales\" : 402\n      }, {\n        \"daily-sales\" : 403\n      }, {\n        \"daily-sales\" : 404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 420\n      }, {\n        \"daily-sales\" : 421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 430\n      }, {\n        \"daily-sales\" : 431\n      }, {\n        \"daily-sales\" : 432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 5\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 510\n      }, {\n        \"daily-sales\" : 511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 520\n      }, {\n        \"daily-sales\" : 521\n      }, {\n        \"daily-sales\" : 522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 530\n      }, {\n        \"daily-sales\" : 531\n      }, {\n        \"daily-sales\" : 532\n      }, {\n        \"daily-sales\" : 533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 6\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 600\n      }, {\n        \"daily-sales\" : 601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 610\n      }, {\n        \"daily-sales\" : 611\n      }, {\n        \"daily-sales\" : 612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 620\n      }, {\n        \"daily-sales\" : 621\n      }, {\n        \"daily-sales\" : 622\n      }, {\n        \"daily-sales\" : 623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 630\n      }, {\n        \"daily-sales\" : 631\n      }, {\n        \"daily-sales\" : 632\n      }, {\n        \"daily-sales\" : 633\n      }, {\n        \"daily-sales\" : 634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 7\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 700\n      }, {\n        \"daily-sales\" : 701\n      }, {\n        \"daily-sales\" : 702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 710\n      }, {\n        \"daily-sales\" : 711\n      }, {\n        \"daily-sales\" : 712\n      }, {\n        \"daily-sales\" : 713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 720\n      }, {\n        \"daily-sales\" : 721\n      }, {\n        \"daily-sales\" : 722\n      }, {\n        \"daily-sales\" : 723\n      }, {\n        \"daily-sales\" : 724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 8\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 800\n      }, {\n        \"daily-sales\" : 801\n      }, {\n        \"daily-sales\" : 802\n      }, {\n        \"daily-sales\" : 803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 810\n      }, {\n        \"daily-sales\" : 811\n      }, {\n        \"daily-sales\" : 812\n      }, {\n        \"daily-sales\" : 813\n      }, {\n        \"daily-sales\" : 814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 830\n      }, {\n        \"daily-sales\" : 831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 9\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 900\n      }, {\n        \"daily-sales\" : 901\n      }, {\n        \"daily-sales\" : 902\n      }, {\n        \"daily-sales\" : 903\n      }, {\n        \"daily-sales\" : 904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 920\n      }, {\n        \"daily-sales\" : 921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 930\n      }, {\n        \"daily-sales\" : 931\n      }, {\n        \"daily-sales\" : 932\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 10\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1000\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1010\n      }, {\n        \"daily-sales\" : 1011\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1020\n      }, {\n        \"daily-sales\" : 1021\n      }, {\n        \"daily-sales\" : 1022\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1030\n      }, {\n        \"daily-sales\" : 1031\n      }, {\n        \"daily-sales\" : 1032\n      }, {\n        \"daily-sales\" : 1033\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 11\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1100\n      }, {\n        \"daily-sales\" : 1101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1110\n      }, {\n        \"daily-sales\" : 1111\n      }, {\n        \"daily-sales\" : 1112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1120\n      }, {\n        \"daily-sales\" : 1121\n      }, {\n        \"daily-sales\" : 1122\n      }, {\n        \"daily-sales\" : 1123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1130\n      }, {\n        \"daily-sales\" : 1131\n      }, {\n        \"daily-sales\" : 1132\n      }, {\n        \"daily-sales\" : 1133\n      }, {\n        \"daily-sales\" : 1134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 12\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1200\n      }, {\n        \"daily-sales\" : 1201\n      }, {\n        \"daily-sales\" : 1202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1210\n      }, {\n        \"daily-sales\" : 1211\n      }, {\n        \"daily-sales\" : 1212\n      }, {\n        \"daily-sales\" : 1213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1220\n      }, {\n        \"daily-sales\" : 1221\n      }, {\n        \"daily-sales\" : 1222\n      }, {\n        \"daily-sales\" : 1223\n      }, {\n        \"daily-sales\" : 1224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 13\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1300\n      }, {\n        \"daily-sales\" : 1301\n      }, {\n        \"daily-sales\" : 1302\n      }, {\n        \"daily-sales\" : 1303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1310\n      }, {\n        \"daily-sales\" : 1311\n      }, {\n        \"daily-sales\" : 1312\n      }, {\n        \"daily-sales\" : 1313\n      }, {\n        \"daily-sales\" : 1314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1330\n      }, {\n        \"daily-sales\" : 1331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 14\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1400\n      }, {\n        \"daily-sales\" : 1401\n      }, {\n        \"daily-sales\" : 1402\n      }, {\n        \"daily-sales\" : 1403\n      }, {\n        \"daily-sales\" : 1404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1420\n      }, {\n        \"daily-sales\" : 1421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1430\n      }, {\n        \"daily-sales\" : 1431\n      }, {\n        \"daily-sales\" : 1432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 15\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1510\n      }, {\n        \"daily-sales\" : 1511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1520\n      }, {\n        \"daily-sales\" : 1521\n      }, {\n        \"daily-sales\" : 1522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1530\n      }, {\n        \"daily-sales\" : 1531\n      }, {\n        \"daily-sales\" : 1532\n      }, {\n        \"daily-sales\" : 1533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 16\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1600\n      }, {\n        \"daily-sales\" : 1601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1610\n      }, {\n        \"daily-sales\" : 1611\n      }, {\n        \"daily-sales\" : 1612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1620\n      }, {\n        \"daily-sales\" : 1621\n      }, {\n        \"daily-sales\" : 1622\n      }, {\n        \"daily-sales\" : 1623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1630\n      }, {\n        \"daily-sales\" : 1631\n      }, {\n        \"daily-sales\" : 1632\n      }, {\n        \"daily-sales\" : 1633\n      }, {\n        \"daily-sales\" : 1634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 17\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1700\n      }, {\n        \"daily-sales\" : 1701\n      }, {\n        \"daily-sales\" : 1702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1710\n      }, {\n        \"daily-sales\" : 1711\n      }, {\n        \"daily-sales\" : 1712\n      }, {\n        \"daily-sales\" : 1713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1720\n      }, {\n        \"daily-sales\" : 1721\n      }, {\n        \"daily-sales\" : 1722\n      }, {\n        \"daily-sales\" : 1723\n      }, {\n        \"daily-sales\" : 1724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 18\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 1800\n      }, {\n        \"daily-sales\" : 1801\n      }, {\n        \"daily-sales\" : 1802\n      }, {\n        \"daily-sales\" : 1803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1810\n      }, {\n        \"daily-sales\" : 1811\n      }, {\n        \"daily-sales\" : 1812\n      }, {\n        \"daily-sales\" : 1813\n      }, {\n        \"daily-sales\" : 1814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1830\n      }, {\n        \"daily-sales\" : 1831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 19\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 1900\n      }, {\n        \"daily-sales\" : 1901\n      }, {\n        \"daily-sales\" : 1902\n      }, {\n        \"daily-sales\" : 1903\n      }, {\n        \"daily-sales\" : 1904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 1910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 1920\n      }, {\n        \"daily-sales\" : 1921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 1930\n      }, {\n        \"daily-sales\" : 1931\n      }, {\n        \"daily-sales\" : 1932\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 20\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2000\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2010\n      }, {\n        \"daily-sales\" : 2011\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2020\n      }, {\n        \"daily-sales\" : 2021\n      }, {\n        \"daily-sales\" : 2022\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2030\n      }, {\n        \"daily-sales\" : 2031\n      }, {\n        \"daily-sales\" : 2032\n      }, {\n        \"daily-sales\" : 2033\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 21\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2100\n      }, {\n        \"daily-sales\" : 2101\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2110\n      }, {\n        \"daily-sales\" : 2111\n      }, {\n        \"daily-sales\" : 2112\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2120\n      }, {\n        \"daily-sales\" : 2121\n      }, {\n        \"daily-sales\" : 2122\n      }, {\n        \"daily-sales\" : 2123\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2130\n      }, {\n        \"daily-sales\" : 2131\n      }, {\n        \"daily-sales\" : 2132\n      }, {\n        \"daily-sales\" : 2133\n      }, {\n        \"daily-sales\" : 2134\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 22\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2200\n      }, {\n        \"daily-sales\" : 2201\n      }, {\n        \"daily-sales\" : 2202\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2210\n      }, {\n        \"daily-sales\" : 2211\n      }, {\n        \"daily-sales\" : 2212\n      }, {\n        \"daily-sales\" : 2213\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2220\n      }, {\n        \"daily-sales\" : 2221\n      }, {\n        \"daily-sales\" : 2222\n      }, {\n        \"daily-sales\" : 2223\n      }, {\n        \"daily-sales\" : 2224\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2230\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 23\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2300\n      }, {\n        \"daily-sales\" : 2301\n      }, {\n        \"daily-sales\" : 2302\n      }, {\n        \"daily-sales\" : 2303\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2310\n      }, {\n        \"daily-sales\" : 2311\n      }, {\n        \"daily-sales\" : 2312\n      }, {\n        \"daily-sales\" : 2313\n      }, {\n        \"daily-sales\" : 2314\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2320\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2330\n      }, {\n        \"daily-sales\" : 2331\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 24\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2400\n      }, {\n        \"daily-sales\" : 2401\n      }, {\n        \"daily-sales\" : 2402\n      }, {\n        \"daily-sales\" : 2403\n      }, {\n        \"daily-sales\" : 2404\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2410\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2420\n      }, {\n        \"daily-sales\" : 2421\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2430\n      }, {\n        \"daily-sales\" : 2431\n      }, {\n        \"daily-sales\" : 2432\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 25\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2500\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2510\n      }, {\n        \"daily-sales\" : 2511\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2520\n      }, {\n        \"daily-sales\" : 2521\n      }, {\n        \"daily-sales\" : 2522\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2530\n      }, {\n        \"daily-sales\" : 2531\n      }, {\n        \"daily-sales\" : 2532\n      }, {\n        \"daily-sales\" : 2533\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 26\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2600\n      }, {\n        \"daily-sales\" : 2601\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2610\n      }, {\n        \"daily-sales\" : 2611\n      }, {\n        \"daily-sales\" : 2612\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2620\n      }, {\n        \"daily-sales\" : 2621\n      }, {\n        \"daily-sales\" : 2622\n      }, {\n        \"daily-sales\" : 2623\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2630\n      }, {\n        \"daily-sales\" : 2631\n      }, {\n        \"daily-sales\" : 2632\n      }, {\n        \"daily-sales\" : 2633\n      }, {\n        \"daily-sales\" : 2634\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 27\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2700\n      }, {\n        \"daily-sales\" : 2701\n      }, {\n        \"daily-sales\" : 2702\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2710\n      }, {\n        \"daily-sales\" : 2711\n      }, {\n        \"daily-sales\" : 2712\n      }, {\n        \"daily-sales\" : 2713\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2720\n      }, {\n        \"daily-sales\" : 2721\n      }, {\n        \"daily-sales\" : 2722\n      }, {\n        \"daily-sales\" : 2723\n      }, {\n        \"daily-sales\" : 2724\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2730\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 28\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 4,\n      \"week\" : [ {\n        \"daily-sales\" : 2800\n      }, {\n        \"daily-sales\" : 2801\n      }, {\n        \"daily-sales\" : 2802\n      }, {\n        \"daily-sales\" : 2803\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2810\n      }, {\n        \"daily-sales\" : 2811\n      }, {\n        \"daily-sales\" : 2812\n      }, {\n        \"daily-sales\" : 2813\n      }, {\n        \"daily-sales\" : 2814\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2820\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2830\n      }, {\n        \"daily-sales\" : 2831\n      } ]\n    } ]\n  } ]\n}",
		"{\n  \"Location-Details\" : [ {\n    \"Test-id\" : \"line 29\",\n    \"a4\" : [ {\n      \"text\" : \" 0>\",\n      \"week-of-month\" : 5,\n      \"week\" : [ {\n        \"daily-sales\" : 2900\n      }, {\n        \"daily-sales\" : 2901\n      }, {\n        \"daily-sales\" : 2902\n      }, {\n        \"daily-sales\" : 2903\n      }, {\n        \"daily-sales\" : 2904\n      } ]\n    }, {\n      \"text\" : \" 1>\",\n      \"week-of-month\" : 1,\n      \"week\" : [ {\n        \"daily-sales\" : 2910\n      } ]\n    }, {\n      \"text\" : \" 2>\",\n      \"week-of-month\" : 2,\n      \"week\" : [ {\n        \"daily-sales\" : 2920\n      }, {\n        \"daily-sales\" : 2921\n      } ]\n    }, {\n      \"text\" : \" 3>\",\n      \"week-of-month\" : 3,\n      \"week\" : [ {\n        \"daily-sales\" : 2930\n      }, {\n        \"daily-sales\" : 2931\n      }, {\n        \"daily-sales\" : 2932\n      } ]\n    } ]\n  } ]\n}",
	};
//	public void testUpdate() throws IOException {
//		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61.cbl";
//		ICobolIOBuilder ioBuilder = CobolIoProvider.getInstance()
//				.newIOBuilder(copybookFileName, ICopybookDialects.FMT_MAINFRAME);
//		AbstractLine line;
//		
//		for (int i = 0; i < LINES.length; i++) {
//			line = ioBuilder.newLine();
//			line.getFieldValue("Test-id").set("line " + i);
//			
//			for (int j = 0; j < 4; j++) {
//				int count = (i + j) % 5 + 1;
//				line.getFieldValue("text (" + j + ")").set(" " + j + ">");
//				line.getFieldValue("week-of-month (" + j + ")").set(count);
//				
//				for (int k = 0; k < count; k++) {
//					String index = " (" + j + ", " + k + ")";
//					line.getFieldValue("sep" + index)          .set(" ");
//					line.getFieldValue("daily-sales" + index)  .set(i * 100 + j * 10 + k);
//				}
//			}
//			assertEquals(LINES[i], line.getFullLine());
//		}
//	}
	

	public void testConversionToXml1() throws IOException,  XMLStreamException {
		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61a.cbl";

		
		ICobol2Json cbl2Xml = Cobol2Json.newCobol2Json(copybookFileName)
				.setDialect(ICopybookDialects.FMT_GNU_COBOL);
		
		for (int i = 0; i < LINES.length; i++) {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			cbl2Xml.cobol2json(new ByteArrayInputStream(LINES[i].getBytes()), os);
			
			assertEquals(i + "", EXPECTED_JSON1[i], Conversion.replace(os.toString(),"\r", "").toString());
//			System.out.println();
//			System.out.println(LINES[i]);
//			System.out.println(new String(os.toByteArray()));
		}
	}

	public void testConversionToXml2() throws IOException,  XMLStreamException {
		String copybookFileName = TstXmlConstants.COBOL_DIRECTORY + "OccursDependingOn61.cbl";

		
		ICobol2Json cbl2Xml = Cobol2Json.newCobol2Json(copybookFileName)
				.setDialect(ICopybookDialects.FMT_GNU_COBOL);
		
		System.out.println();
		System.out.println();
		for (int i = 0; i < LINES.length; i++) {
			ByteArrayOutputStream os = new ByteArrayOutputStream();
			cbl2Xml.cobol2json(new ByteArrayInputStream(LINES[i].getBytes()), os);

			assertEquals(EXPECTED_JSON2[i], Conversion.replace(os.toString(),"\r", "").toString());

//			assertEquals(EXPECTED_JSON[i], new String(os.toByteArray()));
//			System.out.println();
//			System.out.println(LINES[i]);
//			System.out.println(new String(os.toByteArray()));
		}
	}



}
