package example;
 /*
  *   This code was generated by JRecord projects CodeGen program
  *   on the 7 Sep 2015 10:46:37
  *   It is should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   reponsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  */

import java.io.IOException;

import net.sf.JRecord.JRecordInterface1;
import net.sf.JRecord.Common.Constants;
import net.sf.JRecord.Common.RecordException;
import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.External.CopybookLoader;
import net.sf.JRecord.IO.AbstractLineWriter;
import net.sf.JRecord.def.IO.builders.ICobolIOBuilder;

import example.ioBuilderWithSchema.schema.RecordDtar020;
import example.ioBuilderWithSchema.schema.SchemaDtar020;


/**
 * Write Cobol file using a Cobol Copybook (Dtar020).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify 
 * it according to needs
 */
public final class WriteDtar020 {

    private String testDir        = "G:/temp/";
    private String salesFileOut   = testDir + "DTAR020out.bin";
    private String copybookName   = "/F:/Work/EclipseWorkspaces/std_workspace/JRecord_CodeGen/bin/test/gen/DTAR020.cbl"; 

    private RecordDtar020 rDtar020;
    
    /**
     * Example of LineReader  classes
     */
    public WriteDtar020() {
        super();

        try {
            ICobolIOBuilder iob = JRecordInterface1.COBOL
                                       .newIOBuilder(copybookName)
                                           .setFont("CP037")
                                           .setFileOrganization(Constants.IO_FIXED_LENGTH)
                                           .setSplitCopybook(CopybookLoader.SPLIT_NONE)
                                           .setDropCopybookNameFromFields(true);  
            SchemaDtar020 schemaDtar020
                    = new SchemaDtar020(iob.getLayout()); 
            rDtar020 = schemaDtar020.recordDtar020;
            AbstractLineWriter writer = iob.newWriter(salesFileOut);
 
            writer.write(createDtar020(iob, 11));
            writer.write(createDtar020(iob, 22));
            writer.write(createDtar020(iob, 33));
            writer.write(createDtar020(iob, 44));

            writer.close();
        } catch (Exception e) {
             System.out.println();

            e.printStackTrace();
        }
    }

    private AbstractLine createDtar020(ICobolIOBuilder iob, int data) throws RecordException, IOException {
        AbstractLine l = iob.newLine();    
        
        l.getFieldValue(rDtar020.fldKeycodeNo).set(data);
        l.getFieldValue(rDtar020.fldStoreNo).set(data);
        l.getFieldValue(rDtar020.fldDate).set(data);
        l.getFieldValue(rDtar020.fldDeptNo).set(data);
        l.getFieldValue(rDtar020.fldQtySold).set(data);
        l.getFieldValue(rDtar020.fldSalePrice).set(data);
    
        return l;
    }

    public static void main(String[] args) {
        new WriteDtar020();
    }
}

